# Generated by Django 3.2.9 on 2021-12-08 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriete_dite', models.CharField(blank=True, max_length=250, null=True)),
                ('titre_fonciere', models.CharField(blank=True, max_length=250, null=True)),
                ('nature', models.CharField(blank=True, choices=[('Copropriété', 'Copropriété'), ('Mise à jour', 'Mise à jour'), ('Copropriété et mise à jour', 'Copropriété et mise à jour'), ('Copropriété, mise à jour, et fusion', 'Copropriété, mise à jour, et fusion'), ('Morcellement', 'Morcellement'), ('Fusion', 'Fusion'), ('Morcellement et fusion', 'Morcellement et fusion'), ('Morcellement et mise à jour', 'Morcellement et mise à jour'), ('Délimitation', 'Délimitation'), ('Plan cote', 'Plan cote'), ('Implantation', 'Implantation'), ('Rétablissement', 'Rétablissement'), ('Avenant', 'Avenant')], max_length=250, null=True)),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('ref_proprietaire_1', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('ref_proprietaire_2', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cadastre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.cadastre')),
                ('numero_du_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.dossier')),
                ('utilisateur', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
