# Generated by Django 3.2.9 on 2021-12-08 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(blank=True, choices=[('En cours', 'En cours'), ('Terrain', 'Terrain'), ('Bureau', 'Bureau'), ('Instance', 'Instance'), ('Complet', 'Complet'), ('Cadastre', 'Cadastre'), ('Scanner', 'Scanner')], max_length=250, null=True)),
                ('date_de_envoie', models.DateField(blank=True, null=True)),
                ('date_de_recepisse', models.DateField(blank=True, null=True)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('agent_de_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_de_bureau', to=settings.AUTH_USER_MODEL)),
                ('agent_de_terrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_de_terrain', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
